version: '0.1'

services:
  develop:
    build: ./client
    image: maxsloof/basedlibrarian-client
    tty: true
    volumes:
      - ./client/code:/app/code
      - ./books:/app/books
      # - ./models:/app/models
    command: python code/main.py
    env_file:
      - ./.env